name: Node CI

on: [push]
jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v1

            -   name: Setup SSH Keys and known_hosts
                env:
                    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
                run: |
                    mkdir -p ~/.ssh
                    ssh-keyscan github.com >> ~/.ssh/known_hosts
                    ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                    ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
                    sudo apt update -y \
                    && sudo apt install -y software-properties-common \
                    && sudo add-apt-repository ppa:deadsnakes/ppa \
                    && sudo apt install python3-pip python3.7 python3.7-venv -y \
                    && sudo python3.7 -m pip install --upgrade pip \
                    && sudo rm -rf /var/lib/apt/lists/*

            -   name: Some task that fetches dependencies
                env:
                    key: eval $(ssh-agent) > /dev/null
                    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
                run: ./fetch-deps.sh
